name: flutter_image_compress
description: Compress Pictures. Can effectively reduce the size of the transmission.
repository: https://github.com/fluttercandies/flutter_image_compress
publish_to: 'none'
version: 2.3.0

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_image_compress_common:
    git:
      url: https://github.com/flrnsbt/flutter_image_compress
      path: packages/flutter_image_compress_common
      ref: web-lazy-pica-load
  flutter_image_compress_web:
    git:
      url: https://github.com/flrnsbt/flutter_image_compress
      path: packages/flutter_image_compress_web
      ref: web-lazy-pica-load
  flutter_image_compress_macos:
    git:
      url: https://github.com/flrnsbt/flutter_image_compress
      path: packages/flutter_image_compress_macos
      ref: web-lazy-pica-load
  flutter_image_compress_ohos:
    git:
      url: https://github.com/flrnsbt/flutter_image_compress
      path: packages/flutter_image_compress_ohos
      ref: web-lazy-pica-load
  flutter_image_compress_platform_interface:
    git:
      url: https://github.com/flrnsbt/flutter_image_compress
      path: packages/flutter_image_compress_platform_interface
      ref: web-lazy-pica-load



flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_image_compress_common
      ios:
        default_package: flutter_image_compress_common
      macos:
        default_package: flutter_image_compress_macos
      web:
        default_package: flutter_image_compress_web
